removes lengthy note on fix for #144 in source code
Note: prevent import error in production by importing shorteners directoy instead of

  from pyshorteners import Shortener

which loads all shorteners from all python modules from its subfolder. Creating
a build with pyinstaller seems to leave the submodules out, because submodules
can then not be imported in a production build with error

  ModuleNotFoundError: No module named 'pyshorteners.shorteners'